name: ASP.NET Web App Build

on:
  push:
    paths:
      - '.github/workflows/aspnet-webapp-build.yml'
      - 'src/dotnet/WebApp/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # For Windows, use: runs-on: windows-latest
    # For macOS, use: runs-on: macos-latest
    # For self-hosted, use: runs-on: self-hosted
    # For ARC Runner, use: runs-on: arc-runner-set
    defaults:
      run:
        working-directory: ./src/dotnet/WebApp
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.x'

      - name: Build Code
        run: dotnet build --configuration Release

      - name: Publish Code
        run: dotnet publish -c Release --property:PublishDir="${{runner.temp}}/webapp"
