name: Express Server without cache

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/javascript/express-hello-world/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd src/javascript/express-hello-world
          npm install

      - name: Show installed packages
        run: |
          cd src/javascript/express-hello-world
          npm list
